-- Vendors and Products Population SQL Script
-- Generated automatically for Zora African Market
-- Execute this script using Supabase MCP execute_sql tool
--
-- IMPORTANT: This script assumes users and profiles have been created via Auth.
-- Run create-users-auth.js and update-profiles.js first.

BEGIN;

-- Cleanup: Delete existing vendors and their products to avoid conflicts
-- This ensures a clean slate for population
-- Delete by both ID and slug to catch all potential conflicts
DELETE FROM public.products WHERE vendor_id IN (
    SELECT id FROM public.vendors WHERE 
        id IN (
            '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', '27204b60-8d78-4d0a-a5e7-b73716db979b',
            'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', '010d5834-6ba4-4aac-a1fc-c0296c31be86',
            '286d503b-560f-46a3-b877-b6b5edae2038', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f',
            '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', '8c593b02-46ae-42ce-ac58-5ef220058850',
            'fad19083-5fa8-4405-941c-3ac0c40aa4c9', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223',
            '1c294684-d263-4ce8-a24a-0fa8b4f714a0', 'b153214c-ee9c-4014-823d-70a0ce7c00e7',
            '7c7adf08-a2c9-4690-96f1-761731686b01', '2c17828d-b39f-4751-a0a4-52e215af0412',
            '6e17ee6e-ae1a-44c1-96ed-12d81db1d145', '2a365e9a-dac9-4d89-996c-6279f0964db1',
            '7310b1b9-459f-418c-b1ed-d7f90fc90b6d', '1c1ba3b9-cc67-4052-afcd-6aa276fd0c43',
            'e4b8d916-257e-4aed-be00-9fe60cd8d87f', 'b90611e2-b35a-4c68-beb3-23962ab301af'
        )
        OR slug IN (
            'east-africa-market', 'kenya-delights', 'authentic-south-africa', 'south-africa-groceries',
            'taste-of-south-africa', 'south-africa-market', 'south-africa-delights', 'authentic-north-africa',
            'south-africa-groceries-2', 'taste-of-north-africa', 'east-africa-market-2', 'nigeria-delights',
            'authentic-east-africa', 'west-africa-groceries', 'taste-of-north-africa-2', 'north-africa-market',
            'south-africa-delights-2', 'authentic-west-africa', 'east-africa-groceries', 'taste-of-east-africa'
        )
);

DELETE FROM public.vendors WHERE 
    id IN (
        '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', '27204b60-8d78-4d0a-a5e7-b73716db979b',
        'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', '010d5834-6ba4-4aac-a1fc-c0296c31be86',
        '286d503b-560f-46a3-b877-b6b5edae2038', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f',
        '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', '8c593b02-46ae-42ce-ac58-5ef220058850',
        'fad19083-5fa8-4405-941c-3ac0c40aa4c9', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223',
        '1c294684-d263-4ce8-a24a-0fa8b4f714a0', 'b153214c-ee9c-4014-823d-70a0ce7c00e7',
        '7c7adf08-a2c9-4690-96f1-761731686b01', '2c17828d-b39f-4751-a0a4-52e215af0412',
        '6e17ee6e-ae1a-44c1-96ed-12d81db1d145', '2a365e9a-dac9-4d89-996c-6279f0964db1',
        '7310b1b9-459f-418c-b1ed-d7f90fc90b6d', '1c1ba3b9-cc67-4052-afcd-6aa276fd0c43',
        'e4b8d916-257e-4aed-be00-9fe60cd8d87f', 'b90611e2-b35a-4c68-beb3-23962ab301af'
    )
    OR slug IN (
        'east-africa-market', 'kenya-delights', 'authentic-south-africa', 'south-africa-groceries',
        'taste-of-south-africa', 'south-africa-market', 'south-africa-delights', 'authentic-north-africa',
        'south-africa-groceries-2', 'taste-of-north-africa', 'east-africa-market-2', 'nigeria-delights',
        'authentic-east-africa', 'west-africa-groceries', 'taste-of-north-africa-2', 'north-africa-market',
        'south-africa-delights-2', 'authentic-west-africa', 'east-africa-groceries', 'taste-of-east-africa'
    );

-- Insert Vendors
INSERT INTO public.vendors (
    id, user_id, shop_name, slug, description, logo_url, cover_image_url,
    address, latitude, longitude, coverage_radius_km, is_verified,
    rating, review_count, cultural_specialties, categories,
    delivery_time_min, delivery_time_max, delivery_fee, minimum_order,
    is_featured, badge, created_at, updated_at
) VALUES
    ('2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'e3ba13cb-0f8b-425b-b2db-88393cdcd172', 'East Africa Market', 'east-africa-market', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '121 Avenue, Hackney, London', 51.57879, -0.013828, 12.56, TRUE, 4, 500, ARRAY['Kenya'], ARRAY['Spices', 'Grains', 'Vegetables'], 30, 74, 5.65, 20.41, FALSE, 'Verified', NOW(), NOW()),
    ('27204b60-8d78-4d0a-a5e7-b73716db979b', '0c427d4e-03b1-44d8-8242-fee48a342e4e', 'Kenya Delights', 'kenya-delights', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '181 High Street, Brixton, London', 51.453485, -0.069545, 12.61, TRUE, 4.3, 109, ARRAY['Kenya'], ARRAY['Spices', 'Grains', 'Vegetables'], 33, 53, 5.44, 15.34, FALSE, NULL, NOW(), NOW()),
    ('f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'beedde86-5814-41bb-930b-e0fe6d10e412', 'Authentic South Africa', 'authentic-south-africa', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '108 Avenue, Peckham, London', 51.482327999999995, -0.03972199999999999, 6.26, TRUE, 4.5, 402, ARRAY['South Africa', 'Zimbabwe', 'Botswana'], ARRAY['Spices', 'Grains'], 36, 85, 5.67, 29.9, FALSE, NULL, NOW(), NOW()),
    ('010d5834-6ba4-4aac-a1fc-c0296c31be86', '13bc7cc5-e8f5-47aa-b0a9-4da951a7ef1f', 'South Africa Groceries', 'south-africa-groceries', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '3 High Street, Hackney, London', 51.503896, -0.014261999999999997, 10.57, FALSE, 4.6, 330, ARRAY['South Africa'], ARRAY['Spices', 'Grains'], 35, 85, 5.7, 17.55, FALSE, 'Verified', NOW(), NOW()),
    ('286d503b-560f-46a3-b877-b6b5edae2038', '468e96af-7135-4482-aa20-a2e883cce3e9', 'Taste of South Africa', 'taste-of-south-africa', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '66 High Street, Brixton, London', 51.413854, -0.161354, 9.78, FALSE, 4.3, 489, ARRAY['South Africa', 'Zimbabwe'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 27, 81, 4.77, 22.76, FALSE, 'Fast Delivery', NOW(), NOW()),
    ('c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', '6bb1b9a3-eeae-47e6-ae49-3bfb6da2429a', 'South Africa Market', 'south-africa-market', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '10 Road, Brixton, London', 51.495945, -0.100163, 13.13, TRUE, 4.4, 135, ARRAY['South Africa', 'Zimbabwe', 'Botswana'], ARRAY['Spices', 'Grains', 'Vegetables'], 38, 47, 4.69, 29.49, FALSE, NULL, NOW(), NOW()),
    ('0e130aae-0e69-401c-a49b-eb79fcf1c1ea', '7e7856cf-8164-4c4b-8a78-ea18d055bc72', 'South Africa Delights', 'south-africa-delights', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '45 Road, Brixton, London', 51.443338999999995, -0.14841000000000001, 9.17, FALSE, 4.6, 309, ARRAY['South Africa'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 40, 65, 4.43, 16.08, TRUE, 'Fast Delivery', NOW(), NOW()),
    ('8c593b02-46ae-42ce-ac58-5ef220058850', '0e45d3b5-977b-4161-a856-1869510f3ea7', 'Authentic North Africa', 'authentic-north-africa', 'Your trusted source for authentic North Africa products. We bring the flavors and traditions of North Africa to your doorstep.', NULL, NULL, '108 Lane, Camden, London', 51.535928, -0.09869899999999998, 9.7, TRUE, 4.9, 99, ARRAY['Morocco', 'Egypt', 'Tunisia'], ARRAY['Spices', 'Grains'], 40, 61, 5.41, 25.26, FALSE, NULL, NOW(), NOW()),
    ('fad19083-5fa8-4405-941c-3ac0c40aa4c9', '639c37af-2026-4120-b327-2973e90f40d3', 'South Africa Groceries', 'south-africa-groceries-2', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '153 Lane, Brixton, London', 51.436139999999995, -0.114732, 8.19, TRUE, 4.4, 167, ARRAY['South Africa'], ARRAY['Spices', 'Grains', 'Vegetables'], 30, 62, 4.64, 28.61, TRUE, NULL, NOW(), NOW()),
    ('f7b0c3c3-3a58-48c5-bfbd-6ba217702223', '84bf7dcd-a342-4717-bc58-7064963a9987', 'Taste of North Africa', 'taste-of-north-africa', 'Your trusted source for authentic North Africa products. We bring the flavors and traditions of North Africa to your doorstep.', NULL, NULL, '84 Lane, Tottenham, London', 51.635217000000004, -0.073864, 10.43, TRUE, 4.2, 454, ARRAY['Morocco', 'Egypt', 'Tunisia'], ARRAY['Spices', 'Grains', 'Vegetables'], 20, 47, 3.07, 24.13, FALSE, NULL, NOW(), NOW()),
    ('1c294684-d263-4ce8-a24a-0fa8b4f714a0', 'b0cafd63-63bb-43a3-8cb1-431f92f920dc', 'East Africa Market', 'east-africa-market-2', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '80 Road, Camden, London', 51.578578, -0.18359299999999998, 5.57, TRUE, 4.6, 239, ARRAY['Kenya'], ARRAY['Spices', 'Grains', 'Vegetables'], 25, 45, 3.65, 25.69, FALSE, NULL, NOW(), NOW()),
    ('b153214c-ee9c-4014-823d-70a0ce7c00e7', 'f2bdabe4-5364-4663-bf29-08fd897e16ac', 'Nigeria Delights', 'nigeria-delights', 'Your trusted source for authentic West Africa products. We bring the flavors and traditions of West Africa to your doorstep.', NULL, NULL, '18 Road, Hackney, London', 51.577112, -0.066535, 14.01, TRUE, 4.1, 216, ARRAY['Nigeria', 'Ghana'], ARRAY['Spices', 'Grains', 'Vegetables'], 29, 83, 5.64, 25.72, FALSE, NULL, NOW(), NOW()),
    ('7c7adf08-a2c9-4690-96f1-761731686b01', 'f794a3de-7fca-410a-b408-49686f4c911d', 'Authentic East Africa', 'authentic-east-africa', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '3 Avenue, Brixton, London', 51.494012, -0.144425, 7.14, FALSE, 4.5, 488, ARRAY['Kenya', 'Tanzania'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 36, 85, 4.82, 16.86, FALSE, NULL, NOW(), NOW()),
    ('2c17828d-b39f-4751-a0a4-52e215af0412', '78ff51f0-1021-45d2-9b07-600e18f72b0b', 'West Africa Groceries', 'west-africa-groceries', 'Your trusted source for authentic West Africa products. We bring the flavors and traditions of West Africa to your doorstep.', NULL, NULL, '71 High Street, Camden, London', 51.553467, -0.09431499999999998, 14.39, FALSE, 4.3, 448, ARRAY['Nigeria'], ARRAY['Spices', 'Grains'], 37, 51, 3.29, 15.72, TRUE, NULL, NOW(), NOW()),
    ('6e17ee6e-ae1a-44c1-96ed-12d81db1d145', 'ee068d35-10a7-4007-90a7-a912923ec7c9', 'Taste of North Africa', 'taste-of-north-africa-2', 'Your trusted source for authentic North Africa products. We bring the flavors and traditions of North Africa to your doorstep.', NULL, NULL, '191 Lane, Peckham, London', 51.440877, -0.055865, 14.2, TRUE, 4.8, 142, ARRAY['Morocco', 'Egypt', 'Tunisia'], ARRAY['Spices', 'Grains', 'Vegetables'], 26, 46, 3.47, 17.46, FALSE, NULL, NOW(), NOW()),
    ('2a365e9a-dac9-4d89-996c-6279f0964db1', '21cad22a-f5d0-4371-89a6-ae2f1b48f3de', 'North Africa Market', 'north-africa-market', 'Your trusted source for authentic North Africa products. We bring the flavors and traditions of North Africa to your doorstep.', NULL, NULL, '13 Road, Tottenham, London', 51.628075, -0.07558, 12.71, FALSE, 4.6, 210, ARRAY['Morocco', 'Egypt', 'Tunisia'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 37, 76, 4.94, 21.93, FALSE, NULL, NOW(), NOW()),
    ('7310b1b9-459f-418c-b1ed-d7f90fc90b6d', 'cb60f7ea-95be-49a1-81d5-a52d65c965c6', 'South Africa Delights', 'south-africa-delights-2', 'Your trusted source for authentic South Africa products. We bring the flavors and traditions of South Africa to your doorstep.', NULL, NULL, '95 High Street, Camden, London', 51.540046, -0.153026, 8.88, TRUE, 4.8, 99, ARRAY['South Africa'], ARRAY['Spices', 'Grains'], 35, 86, 3.66, 21.11, TRUE, NULL, NOW(), NOW()),
    ('1c1ba3b9-cc67-4052-afcd-6aa276fd0c43', '92333c7b-f7d4-4332-946e-8213f324e0d8', 'Authentic West Africa', 'authentic-west-africa', 'Your trusted source for authentic West Africa products. We bring the flavors and traditions of West Africa to your doorstep.', NULL, NULL, '107 Avenue, Camden, London', 51.548862, -0.13846299999999997, 8.11, TRUE, 4.3, 392, ARRAY['Nigeria', 'Ghana'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 26, 67, 4.65, 15, FALSE, NULL, NOW(), NOW()),
    ('e4b8d916-257e-4aed-be00-9fe60cd8d87f', '776a5925-a1ff-488b-89f8-2a7ddbbf666a', 'East Africa Groceries', 'east-africa-groceries', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '151 High Street, Tottenham, London', 51.558571, -0.058827, 13.68, TRUE, 4.8, 29, ARRAY['Kenya', 'Tanzania', 'Ethiopia'], ARRAY['Spices', 'Grains', 'Vegetables', 'Meats'], 24, 58, 3.19, 26.43, FALSE, NULL, NOW(), NOW()),
    ('b90611e2-b35a-4c68-beb3-23962ab301af', '46afdc7a-55f2-4324-8396-ad1478b597fc', 'Taste of East Africa', 'taste-of-east-africa', 'Your trusted source for authentic East Africa products. We bring the flavors and traditions of East Africa to your doorstep.', NULL, NULL, '28 Avenue, Brixton, London', 51.465726, -0.073126, 7.22, TRUE, 4.8, 70, ARRAY['Kenya'], ARRAY['Spices', 'Grains'], 38, 85, 5.32, 20.54, FALSE, NULL, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
    shop_name = EXCLUDED.shop_name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    updated_at = NOW();



-- Insert Products
INSERT INTO public.products (
    id, vendor_id, name, description, price, unit_price_label,
    stock_quantity, category, cultural_region, image_urls,
    weight, certifications, nutrition, heritage_story,
    is_active, is_featured, badge, rating, review_count,
    created_at, updated_at
) VALUES
    ('6d893bca-c370-4126-9c2a-655b8e3f4431', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'Baklava with spiced nuts, ricotta & chocolate', 'step 1
First, make the syrup. Tip the sugar into a large saucepan with 650ml water. Stir over a low heat until the sugar has dissolved, then turn up the heat and bring to the boil. Reduce the heat to a simmer and cook for 15 mins, then squeeze in a few drops of lemon juice and simmer for a further 5 mins. Remove from the heat and leave to cool. Meanwhile, for assembling the baklava later, melt the butter in a small pan over a low heat for 5 mins, skimming and discarding any froth that rises to the surface.

step 2
For the filling, crush all of the nuts in a pestle and mortar, or blitz in a food processor – you want a mixture of finely ground nuts with a few chunky pieces. Tip into a bowl, stir through the spices and set aside.

step 3
In a separate bowl, mix the ricotta with the lemon and orange zests and vanilla. Heat the oven to 180C/160C fan/gas 4. Brush the bottom of a large baking tray (about 35 x 47cm) with some of the melted butter. Working with one sheet of filo at a tim', 45.07, 'per portion', 21, 'Vegetables', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/ytme8t1764111401.jpg'], '359g', ARRAY['Top Rated'], '{"calories":331,"protein":10,"carbs":78,"fat":25}'::JSONB, 'This traditional Baklava with spiced nuts, ricotta & chocolate has been passed down through generations in North Africa.', TRUE, FALSE, NULL, 3.7, 40, NOW(), NOW()),
    ('11005cbe-3f64-4138-92e3-526a1754f3ee', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'Sugar Pie', 'Preheat oven to 350 degrees F (175 degrees C). Grease a 9-inch pie dish.
Place the brown sugar and butter in a mixing bowl, and beat them together with an electric mixer until creamy and very well combined, without lumps. Beat in eggs, one at a time, incorporating the first egg before adding the next one. Add the vanilla extract and salt; beat the flour in, a little at a time, and then the milk, making a creamy batter. Pour the batter into the prepared pie dish.
Bake in the preheated oven for 35 minutes; remove pie, and cover the rim with aluminum foil to prevent burning. Return to oven, and bake until the middle sets and the top forms a crusty layer, about 15 more minutes. Let the pie cool to room temperature, then refrigerate for at least 1 hour before serving.', 25.35, 'per portion', 50, 'Textiles', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg'], '389g', ARRAY['Organic', 'Top Rated'], '{"calories":630,"protein":48,"carbs":45,"fat":30}'::JSONB, 'This traditional Sugar Pie has been passed down through generations in East Africa.', TRUE, TRUE, NULL, 4.5, 40, NOW(), NOW()),
    ('35c112d5-e84a-423f-ab95-5fb2db51baad', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'Syrian Rice with Meat', 'Heat 1/4 cup butter in a large saucepan over medium-high heat. Add ground beef and season with salt, allspice, cinnamon, and black pepper. Cook and stir until beef is browned and crumbly, 7 to 10 minutes.

Stir chicken broth and rice into beef in the saucepan; bring to a boil. Reduce heat to low, cover, and cook until liquid is absorbed, about 20 minutes.

Meanwhile, melt 2 tablespoons butter in a small skillet over medium heat. Cook and stir pine nuts in hot butter until lightly browned, 3 to 5 minutes.

Mix pine nuts into beef-rice mixture before serving.', 47.81, 'per portion', 20, 'Grains', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/zg2b9l1760524940.jpg'], '873g', ARRAY[]::TEXT[], '{"calories":655,"protein":31,"carbs":71,"fat":30}'::JSONB, 'This traditional Syrian Rice with Meat has been passed down through generations in South Africa.', TRUE, FALSE, NULL, 4.9, 119, NOW(), NOW()),
    ('0d2b6e4e-d76a-4f7f-8342-f5279ebd4b7f', '286d503b-560f-46a3-b877-b6b5edae2038', 'Bitterballen (Dutch meatballs)', 'Melt the butter in a skillet or pan. When melted, add the flour little by little and stir into a thick paste. Slowly stir in the stock, making sure the roux absorbs the liquid. Simmer for a couple of minutes on a low heat while you stir in the onion, parsley and the shredded meat. The mixture should thicken and turn into a heavy, thick sauce.

Pour the mixture into a shallow container, cover and refrigerate for several hours, or until the sauce has solidified.

Take a heaping tablespoon of the cold, thick sauce and quickly roll it into a small ball. Roll lightly through the flour, then the egg and finally the breadcrumbs. Make sure that the egg covers the whole surface of the bitterbal. When done, refrigerate the snacks while the oil in your fryer heats up to 190C (375F). Fry four bitterballen at a time, until golden.

Serve on a plate with a nice grainy or spicy mustard.
', 40.76, 'per portion', 86, 'Meats', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg'], '686g', ARRAY['Organic'], '{"calories":741,"protein":31,"carbs":51,"fat":17}'::JSONB, 'This traditional Bitterballen (Dutch meatballs) has been passed down through generations in Central Africa.', TRUE, FALSE, NULL, 4.2, 52, NOW(), NOW()),
    ('43d5acea-fb6b-4250-8c1f-304373b8ea17', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Jamaican Instant Pot Rice and Beans', 'Instructions

Set Instant Pot to "Sauté." Once Hot, add olive oil. Then add yellow onion and stir until softened, about 3 minutes. Add garlic and green onions and stir for about 30 more seconds.
Press “Cancel” on the Instant Pot. Add rice, coconut milk, water, salt, allspice, and black pepper and stir.
Pour undrained kidney beans on top of the rice mixture. Do not stir. Lay sprigs of thyme on top. Cover the Instant Pot, ensuring the valve is set to “Sealing.”
Press “Manual” or “Pressure Cook” on the Instant Pot and set for High pressure for 6 minutes.
Once the pressure cooking time is done, allow it to natural release for 10 minutes, then quick release any remaining pressure by moving valve to "Venting"
Open lid and remove thyme sprigs. Fluff rice with fork and Enjoy!

Stove Top Instructions
Heat olive oil in a large pot over medium heat. Add yellow onion and stir until softened, about 3 minutes. Add garlic and green onions and stir for about 30 more seconds.
Add rice, undr', 44.61, 'per portion', 83, 'Textiles', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/11bvtm1764795135.jpg'], '466g', ARRAY['Top Rated'], '{"calories":452,"protein":28,"carbs":71,"fat":20}'::JSONB, 'This traditional Jamaican Instant Pot Rice and Beans has been passed down through generations in Central Africa.', TRUE, FALSE, NULL, 3.6, 132, NOW(), NOW()),
    ('8796b137-9e00-4d80-a1e1-aaeba291222d', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Sticky Chicken', 'step 1
Make 3 slashes on each of the drumsticks. Mix together the soy, honey, oil, tomato purée and mustard. Pour this mixture over the chicken and coat thoroughly. Leave to marinate for 30 mins at room temperature or overnight in the fridge. Heat oven to 200C/fan 180C/gas 6.

step 2
Tip the chicken into a shallow roasting tray and cook for 35 mins, turning occasionally, until the chicken is tender and glistening with the marinade.', 49.13, 'per portion', 74, 'Grains', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/cj56fs1762340001.jpg'], '258g', ARRAY['Organic'], '{"calories":327,"protein":11,"carbs":46,"fat":13}'::JSONB, 'This traditional Sticky Chicken has been passed down through generations in East Africa.', TRUE, FALSE, 'Best Seller', 3.8, 137, NOW(), NOW()),
    ('2c400a44-2443-41fe-9dfd-1c670e573b19', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Sweet and Sour Chicken', 'Coat the chicken with egg white:
In a bowl, combine the chicken with the egg white, 1/2 teaspoon kosher salt, and cornstarch. Stir to coat the chicken evenly. Let sit for 15 minutes at room temperature or up to overnight in the refrigerator.

Make the sweet and sour sauce:
Whisk together the pineapple juice, vinegar, ketchup, 1/2 teaspoon kosher salt, and brown sugar.

Stir-fry the chicken over high heat:
Heat a large frying pan or wok over high heat until a bead of water instantly sizzles and evaporates. Pour in 1 tablespoon of cooking oil and swirl to coat. It''s important that the pan is very hot.

Add the chicken and spread the pieces out in one layer. Let the chicken fry untouched for 1 minute, until the bottoms are browned.

Flip and fry the other side for 1 minute. The chicken should still be pinkish in the middle. Dish out the chicken onto a clean plate, leaving as much oil in the pan as possible.

Stir-fry the bell pepper and ginger:
Reduce the heat to medium and ', 47.17, 'per portion', 22, 'Spices', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/arzs741766434335.jpg'], '691g', ARRAY['Organic', 'Top Rated'], '{"calories":580,"protein":40,"carbs":33,"fat":8}'::JSONB, 'This traditional Sweet and Sour Chicken has been passed down through generations in South Africa.', TRUE, FALSE, NULL, 3.9, 38, NOW(), NOW()),
    ('b9de5af7-624d-4122-a7f8-5e41fb28385d', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'Tangy cabbage slaw', 'step 1
Whisk together mayonnaise, lemon zest and juice, vinegar, mustard and celery salt in a small bowl, then season generously.

step 2
Add cabbage, carrots, onion and celery. Mix well and refrigerate. Can be made up to 1 day ahead.', 33.78, 'per portion', 71, 'Beverages', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/e2g2r21764367568.jpg'], '627g', ARRAY['Eco-Friendly'], '{"calories":707,"protein":40,"carbs":51,"fat":21}'::JSONB, 'This traditional Tangy cabbage slaw has been passed down through generations in North Africa.', TRUE, TRUE, NULL, 3.6, 86, NOW(), NOW()),
    ('a54de02f-e48f-4be5-a06b-bc8d419d5de1', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'Tamiya', 'oak the beans in water to cover overnight.Drain. If skinless beans are unavailable, rub to loosen the skins, then discard the skins. Pat the beans dry with a towel.
Grind the beans in a food mill or meat grinder.If neither appliance is available, process them in a food processor but only until the beans form a paste. (If blended too smoothly, the batter tends to fall apart during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 minutes.
Shape the bean mixture into 1-inch balls.Flatten slightly and coat with flour.
Heat at least 1½-inches of oil over medium heat to 365 degrees.
Fry the patties in batches, turning once, until golden brown on all sides, about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part of a meze or in pita bread with tomato-cucumber salad and tahina sauce.', 9.18, 'per portion', 21, 'Textiles', 'West Africa', ARRAY['https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg'], '883g', ARRAY[]::TEXT[], '{"calories":697,"protein":41,"carbs":26,"fat":6}'::JSONB, 'This traditional Tamiya has been passed down through generations in West Africa.', TRUE, FALSE, NULL, 4.9, 82, NOW(), NOW()),
    ('c09d56a6-265f-4e63-ac1b-cad94516b3ca', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Sweet and Sour Pork', 'Preparation
1. Crack the egg into a bowl. Separate the egg white and yolk.

Sweet and Sour Pork
2. Slice the pork tenderloin into strips.

3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.

4. Marinade the pork strips for about 20 minutes.

5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.

Sweet and Sour Pork
Cooking Instructions
1. Pour the cooking oil into a wok and heat to 190°C (375°F). Add the marinated pork strips and fry them until they turn brown. Remove the cooked pork from the wok and place on a plate.

2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok, and heat until the oil and sauce are fully combined.

3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork strips to it.

4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly ', 28.04, 'per portion', 17, 'Vegetables', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/1529442316.jpg'], '845g', ARRAY['Organic'], '{"calories":446,"protein":30,"carbs":30,"fat":30}'::JSONB, 'This traditional Sweet and Sour Pork has been passed down through generations in Central Africa.', TRUE, FALSE, 'Best Seller', 3.7, 44, NOW(), NOW()),
    ('692fa988-8cb9-4083-ace0-cb4f42ffbcec', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Grilled aubergines with spicy chickpeas & walnut sauce', 'step 1
Heat 2 tbsp oil in a pan, add the onion and fry until soft and lightly browned, about 10 mins. Add the chilli, ginger and spices and mix well. Stir in the chickpeas, tomatoes and 5 tbsp water, bring to the boil, then simmer for 10 mins. Add a little salt and pepper and the lemon juice.

step 2
Arrange the aubergines over a grill pan. Brush lightly with oil, sprinkle with salt and pepper, then grill until golden. Flip them over, brush again with oil, season and grill again until tender and golden.

step 3
Mix the yogurt with the garlic, most of the walnuts and coriander and a little salt and pepper. Arrange the aubergine slices over a warm platter and spoon over the chickpea mix. Drizzle with the walnut sauce and scatter with the remaining walnuts and coriander.', 24.35, 'per portion', 61, 'Spices', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/ctw3ba1763788978.jpg'], '728g', ARRAY['Organic', 'Top Rated'], '{"calories":748,"protein":24,"carbs":58,"fat":20}'::JSONB, 'This traditional Grilled aubergines with spicy chickpeas & walnut sauce has been passed down through generations in East Africa.', TRUE, FALSE, NULL, 3.7, 56, NOW(), NOW()),
    ('eab19657-b133-437e-83f0-a6a925bcb01e', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'Venezuelan Arepas', 'Preheat oven to 410° F.
Pour the water into a large bowl. Make sure it is room temperature.
Add the salt. Blend well with a mixer, fork or spatula to make sure it dissolves well.
While you continue to beat the mixture, slowly add the corn meal—a little bit at a time.
Once all the flour is added, keep mixing until the corn meal, water and salt are thoroughly blended and dissolved.
Set aside the masa in its bowl. Let it rest for 5 minutes so that the flour is thoroughly hydrated. This type of corn flour does not have any gluten, so it doesn’t need to be kneaded. The masa should be smooth, firm yet malleable.
While waiting for the 5 minutes’ rest, heat your budare (or comal, griddle, cast-iron pan or non-stick pan) over medium heat. Coat with a little bit of the oil.
Fill a small bowl with water to wet your hands to make the arepas.
Take about 2 Tbsp of the masa in your damp hands. The masa should fit easily in your palm so that it is easy to shape into a small ball.

Cross your', 17.13, 'per portion', 63, 'Textiles', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/3hcy191764376285.jpg'], '915g', ARRAY[]::TEXT[], '{"calories":411,"protein":11,"carbs":66,"fat":12}'::JSONB, 'This traditional Venezuelan Arepas has been passed down through generations in North Africa.', TRUE, TRUE, 'Best Seller', 3.6, 24, NOW(), NOW()),
    ('87a09c20-ff38-4040-a97c-e4cd5ac881b7', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Pouding chomeur', 'In a large bowl, with an electric mixer, mix the butter and sugar till the mix is light.
Add eggs and vanilla and mix.
In another bowl, mix flour and baking powder.
Alternate flour mix and milk to the butter mix.
Pour into a 13 inch by 9 inch greased pan.
MAPLE SAUCE.
In a large casserole, bring to boil the syrup, brown sugar, cream and butter and constantly stir.
Reduce heat and and gently cook 2 minutes or till sauce has reduced a little bit.
Pour sauce gently over cake.
Bake at 325°f (160°c) about 35 minutes or till cake is light brown and when toothpick inserted comes out clean.', 33.66, 'per portion', 75, 'Beverages', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/yqqqwu1511816912.jpg'], '462g', ARRAY['Eco-Friendly'], '{"calories":614,"protein":16,"carbs":36,"fat":30}'::JSONB, 'This traditional Pouding chomeur has been passed down through generations in Central Africa.', TRUE, FALSE, NULL, 4.9, 73, NOW(), NOW()),
    ('8d6c6394-177e-45d4-a0ef-4979c5f63ea1', 'fad19083-5fa8-4405-941c-3ac0c40aa4c9', 'Spaghetti alla Carbonara', 'STEP 1
Put a large saucepan of water on to boil.

STEP 2
Finely chop the 100g pancetta, having first removed any rind. Finely grate 50g pecorino cheese and 50g parmesan and mix them together.

STEP 3
Beat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper. Set everything aside.

STEP 4
Add 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked).

STEP 5
Squash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.

STEP 6
While the spaghetti is cooking, fry the pancetta with the garlic. Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic.

STEP 7
Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp. The garlic has now imparted its flavour, so take it out with a slott', 14.84, 'per portion', 95, 'Grains', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg'], '697g', ARRAY['Organic', 'Top Rated'], '{"calories":780,"protein":32,"carbs":21,"fat":18}'::JSONB, 'This traditional Spaghetti alla Carbonara has been passed down through generations in South Africa.', TRUE, FALSE, NULL, 3.7, 136, NOW(), NOW()),
    ('71fea20b-2bbc-48f1-a73b-abde881f7359', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Duck Confit', 'The day before you want to make the dish, scatter half the salt, half the garlic and half of the herbs over the base of a small shallow dish. Lay the duck legs, skin-side up, on top, then scatter over the remaining salt, garlic and herbs. Cover the duck and refrigerate overnight. This can be done up to 2 days ahead.
Pour the wine into a saucepan that will snugly fit the duck legs in a single layer. Brush the salt off the duck legs and place them, skin-side down, in the wine. Cover the pan with a lid and place over a medium heat. As soon as the wine starts to bubble, turn the heat down to the lowest setting and cook for 2 hours, checking occasionally that the liquid is just barely simmering. (If you own a heat diffuser, it would be good to use it here.) After 2 hours, the duck legs should be submerged in their own fat and the meat should feel incredibly tender when prodded. Leave to cool.
The duck legs are now cooked and can be eaten immediately – or you can follow the next step if yo', 34.51, 'per portion', 69, 'Spices', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/wvpvsu1511786158.jpg'], '882g', ARRAY[]::TEXT[], '{"calories":410,"protein":10,"carbs":28,"fat":23}'::JSONB, 'This traditional Duck Confit has been passed down through generations in East Africa.', TRUE, TRUE, NULL, 4.9, 75, NOW(), NOW()),
    ('618cab5e-f98b-480f-84dc-0e3765420270', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'Spanish Tortilla', 'Put a large non-stick frying pan on a low heat. Cook the onion slowly in the oil and butter until soft but not brown – this should take about 15 mins. Add the potatoes, cover the pan and cook for a further 15-20 mins, stirring occasionally to make sure they fry evenly.
When the potatoes are soft and the onion is shiny, crush 2 garlic cloves and stir in, followed by the beaten eggs.
Put the lid back on the pan and leave the tortilla to cook gently. After 20 mins, the edges and base should be golden, the top set but the middle still a little wobbly. To turn it over, slide it onto a plate and put another plate on top, turn the whole thing over and slide it back into the pan to finish cooking. Once cooked, transfer to a plate and serve the tortilla warm or cold, scattered with the chopped parsley.
To accompany, take slices of warmed baguette, stab all over with a fork and rub with the remaining garlic, pile on grated tomatoes and season with sea salt and a drizzle of olive oil.', 49.89, 'per portion', 49, 'Vegetables', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/quuxsx1511476154.jpg'], '493g', ARRAY['Organic', 'Top Rated'], '{"calories":229,"protein":20,"carbs":75,"fat":20}'::JSONB, 'This traditional Spanish Tortilla has been passed down through generations in Central Africa.', TRUE, TRUE, 'New', 3.6, 26, NOW(), NOW()),
    ('3afb4162-f8c0-4ff8-92ad-26f4e7fd4679', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'Braised Beef Chilli', 'Preheat the oven to 120C/225F/gas mark 1.

Take the meat out of the fridge to de-chill. Pulse the onions and garlic in a food processor until finely chopped. Heat 2 tbsp olive oil in a large casserole and sear the meat on all sides until golden.

Set to one side and add another small slug of oil to brown the chorizo. Remove and add the onion and garlic, spices, herbs and chillies then cook until soft in the chorizo oil. Season with salt and pepper and add the vinegar, tomatoes, ketchup and sugar.

Put all the meat back into the pot with 400ml water (or red wine if you prefer), bring up to a simmer and cook, covered, in the low oven.

After 2 hours, check the meat and add the beans. Cook for a further hour and just before serving, pull the meat apart with a pair of forks.', 6.37, 'per portion', 97, 'Meats', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg'], '259g', ARRAY['Top Rated'], '{"calories":298,"protein":46,"carbs":33,"fat":20}'::JSONB, 'This traditional Braised Beef Chilli has been passed down through generations in North Africa.', TRUE, TRUE, NULL, 4.7, 12, NOW(), NOW()),
    ('cf9f4c8f-e936-4839-98bf-1b184a468edb', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Flan', 'For the caramel place 100 grams of sugar in a frying pan without any fat and melt on medium heat. Try not to stir with a spoon, but swirl the pan itself. Let melt until you have an amber color and sugar is fully melted. Fill the bottom of four flan containers with it. Caramel will harden immediately, so you need to be fast. My containers yield about 120 milliliters each.

2
Preheat oven to 150 degrees Celsius and look for a casserole or container all your four flan containers fit into.

3
Heat milk with 45 grams of sugar and the cut and scraped out vanilla pod. The milk does not need to boil, just needs to be heated. Take out vanilla pod after a few minutes. Meanwhile stir the egg yolks and eggs gently, try not to incorporate any air in it. Them pour milk-mix into egg-mix and again only stir very gently. Pour into prepared flan containers and place these into your casserole or container. Boil water and pour the water into the large casserole. Be sure not to touch the flan mixture', 30.88, 'per portion', 80, 'Meats', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/0s80wo1764374393.jpg'], '251g', ARRAY['Organic'], '{"calories":503,"protein":43,"carbs":80,"fat":30}'::JSONB, 'This traditional Flan has been passed down through generations in South Africa.', TRUE, FALSE, 'Limited', 4.1, 106, NOW(), NOW()),
    ('dccda12d-4a73-4f22-a1b2-f1704b2cb622', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Kung Po Prawns', 'Mix the cornflour and 1 tbsp soy sauce, toss in the prawns and set aside for 10 mins. Stir the vinegar, remaining soy sauce, tomato purée, sugar and 2 tbsp water together to make a sauce.

When you’re ready to cook, heat a large frying pan or wok until very hot, then add 1 tbsp oil. Fry the prawns until they are golden in places and have opened out– then tip them out of the pan.

Heat the remaining oil and add the peanuts, chillies and water chestnuts. Stir-fry for 2 mins or until the peanuts start to colour, then add the ginger and garlic and fry for 1 more min. Tip in the prawns and sauce and simmer for 2 mins until thickened slightly. Serve with rice.', 10.15, 'per portion', 53, 'Textiles', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/1525873040.jpg'], '391g', ARRAY['Organic', 'Top Rated'], '{"calories":465,"protein":22,"carbs":76,"fat":5}'::JSONB, 'This traditional Kung Po Prawns has been passed down through generations in East Africa.', TRUE, FALSE, 'Limited', 4.6, 124, NOW(), NOW()),
    ('0c2ab4bf-46b6-4478-8cf5-3d1672fbbdaa', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Brie wrapped in prosciutto & brioche', 'Mix the flour, 1 tsp salt, caster sugar, yeast, milk and eggs together in a mixer using the dough attachment for 5 mins until the dough is smooth. Add the butter and mix for a further 4 mins on medium speed. Scrape the dough bowl and mix again for 1 min. Place the dough in a container, cover with cling film and leave in the fridge for at least 6 hrs before using.
Wrap the Brie in the prosciutto and set aside. Turn out the dough onto a lightly floured surface. Roll into a 25cm circle. Place the wrapped Brie in the middle of the circle and fold the edges in neatly. Put the parcel onto a baking tray lined with baking parchment and brush with beaten egg. Chill in the fridge for 30 mins, then brush again with beaten egg and chill for a further 30 mins. Leave to rise for 1 hr at room temperature. Heat oven to 200C/180C fan/gas 6, then bake for 22 mins. Serve warm.', 12.16, 'per portion', 23, 'Vegetables', 'East Africa', ARRAY['https://www.themealdb.com/images/media/meals/qqpwsy1511796276.jpg'], '709g', ARRAY['Organic'], '{"calories":573,"protein":17,"carbs":53,"fat":15}'::JSONB, 'This traditional Brie wrapped in prosciutto & brioche has been passed down through generations in East Africa.', TRUE, TRUE, NULL, 3.6, 82, NOW(), NOW()),
    ('0e92cc58-eeb6-4f61-9c58-6232b6d0b1cf', '8c593b02-46ae-42ce-ac58-5ef220058850', 'Beef Caldereta', '0.	Heat oil in a cooking pot. Saute onion and garlic until onion softens
1.	Add beef. Saute until the outer part turns light brown.
2.	Add soy sauce. Pour tomato sauce and water. Let boil.
3.	Add Knorr Beef Cube. Cover the pressure cooker. Cook for 30 minutes.
4.	Pan-fry carrot and potato until it browns. Set aside.
5.	Add chili pepper, liver spread and peanut butter. Stir.
6.	Add bell peppers, fried potato and carrot. Cover the pot. Continue cooking for 5 to 7 minutes.
7.	Season with salt and ground black pepper. Serve.
', 16.81, 'per portion', 86, 'Vegetables', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg'], '616g', ARRAY['Top Rated'], '{"calories":430,"protein":44,"carbs":56,"fat":20}'::JSONB, 'This traditional Beef Caldereta has been passed down through generations in Central Africa.', TRUE, TRUE, NULL, 4.2, 6, NOW(), NOW()),
    ('4c06e058-4bb0-4f21-985a-e9e8e80247b5', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'Hot cumin lamb wrap with crunchy slaw & spicy mayo', 'step 1
Heat a griddle pan. Rub the lamb steaks with the oil, cumin and some seasoning. Griddle for about 3-4 mins on each side or until cooked to your liking. Place to one side on a plate to rest.

step 2
In a large bowl, stir the sugar into the vinegar until dissolved. Add the carrots, spring onions, cabbage and some seasoning, and toss together.

step 3
Blitz the whole peppers and the mayo in a food processor. Add a heap of the salad to each flatbread. Slice the lamb, trimming off any excess fat and lay on top of the salad, drizzling with the resting juices. Spoon over the mayo and scatter with a few of the sliced peppers. Roll up and eat. If using pitta, split and stuff. Serve any extra salad on the side.', 30.17, 'per portion', 43, 'Beverages', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/jyylmo1763790808.jpg'], '797g', ARRAY['Organic', 'Top Rated'], '{"calories":452,"protein":28,"carbs":74,"fat":30}'::JSONB, 'This traditional Hot cumin lamb wrap with crunchy slaw & spicy mayo has been passed down through generations in South Africa.', TRUE, FALSE, NULL, 4.3, 84, NOW(), NOW()),
    ('01fb03cf-4ba4-4cea-b3fa-e63f57ba9890', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'Chicken Quinoa Greek Salad', 'Cook the quinoa following the pack instructions, then rinse in cold water and drain thoroughly.

Meanwhile, mix the butter, chilli and garlic into a paste. Toss the chicken fillets in 2 tsp of the olive oil with some seasoning. Lay in a hot griddle pan and cook for 3-4 mins each side or until cooked through. Transfer to a plate, dot with the spicy butter and set aside to melt.

Next, tip the tomatoes, olives, onion, feta and mint into a bowl. Toss in the cooked quinoa. Stir through the remaining olive oil, lemon juice and zest, and season well. Serve with the chicken fillets on top, drizzled with any buttery chicken juices.', 16.94, 'per portion', 50, 'Textiles', 'West Africa', ARRAY['https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg'], '798g', ARRAY['Eco-Friendly'], '{"calories":508,"protein":45,"carbs":51,"fat":7}'::JSONB, 'This traditional Chicken Quinoa Greek Salad has been passed down through generations in West Africa.', TRUE, FALSE, NULL, 3.9, 88, NOW(), NOW()),
    ('e8fbb212-30c3-45f7-b678-cddb9d4b5f4d', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Kenyan Beef Curry', 'Bring the 4 cups of water to a boil in a Dutch oven or soup pot. Add the beef, garlic, and ginger, and stir well. Bring to a gentle simmer, cover, and cook, stirring occasionally, for 20 minutes. If you get any foamy scum on the top, not to worry, simply spoon it away or stir it back in.
Remove from the heat, and drain, but reserve the excess water for later.
Return the pot or Dutch oven to medium heat with the 2 tablespoons of cooking oil. Once the oil is shimmering, add the onions and cook, stirring occasionally, until softened, 5 to 7 minutes.
Add the tomatoes to the onions, and continue cooking, stirring occasionally, until the tomatoes are falling apart, 3 to 5 minutes.
Add the drained beef to the tomato and onion mixture, and stir well. Continue cooking over medium heat for 5 minutes, stirring occasionally.
Add the paprika, pepper, curry powder, tomato paste, and salt to taste, and stir well.
Add back the excess water that was used for cooking the beef, along with enough ex', 49.68, 'per portion', 72, 'Vegetables', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/lqampv1762325397.jpg'], '567g', ARRAY['Organic'], '{"calories":503,"protein":10,"carbs":66,"fat":29}'::JSONB, 'This traditional Kenyan Beef Curry has been passed down through generations in North Africa.', TRUE, FALSE, NULL, 4.2, 0, NOW(), NOW()),
    ('3fedaef4-15cd-41db-aa33-5296597a7678', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'Thai rice noodle salad', 'step 1
Place the noodles and beansprouts in a heatproof bowl and cover with boiling water. Leave for 4 mins, or until the noodles are tender. Drain, then cool under cold running water and drain again. Return to the bowl.

step 2
Stir together the lime zest and juice, fish or soy sauce and sugar. Stir into the noodles with the red onion and lettuce.

step 3
To make with mince, heat a little oil in a non-stick frying pan and stir-fry 500g minced pork, a small knob of grated ginger and pinch cayenne pepper or chilli powder for 10 mins, until the mince is browned and cooked through. Mix into the noodles, divide between four bowls and serve warm.

step 4
To make with steak, make the rice noodle salad. Heat 1 tsp sunflower oil in a frying pan. Tip 2 tbsp sesame seeds onto a plate. Rub 1 tsp oil into 4 x 175g sirloin steaks and press into sesame seeds. Fry for 5 mins for medium rare, turning halfway. Leave to rest for 5 mins, then thinly slice. Toss 1 deseeded and shredded red chill', 10.93, 'per portion', 20, 'Spices', 'Central Africa', ARRAY['https://www.themealdb.com/images/media/meals/6g3rso1763486069.jpg'], '583g', ARRAY['Organic', 'Top Rated'], '{"calories":619,"protein":11,"carbs":37,"fat":5}'::JSONB, 'This traditional Thai rice noodle salad has been passed down through generations in Central Africa.', TRUE, FALSE, NULL, 4.1, 23, NOW(), NOW()),
    ('b898bf82-78fd-4582-a0d9-d3f77a35889b', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'Chinese Tomato Egg Stir Fry', 'You can use chicken broth in place of the chicken bouillon powder. Add 1/4 cup of broth followed by 2 teaspoons of cornstarch dissolved in 1 tablespoPrepare the tomatoes:
Slice the tomatoes in half. Remove the tough stem from each half that connects to the vine. Cut each half into equal thirds (you’ll get 6 slices from each tomato).

Make the soft scrambled eggs:
In a cold, 8 to 10-inch nonstick skillet, add the vegetable oil and beaten eggs. Turn the heat to medium. Once a thin layer of eggs is just beginning to cook on the bottom, push the eggs in one direction to create layers of scrambled eggs.

Cook, gently stirring the whole time, until the scramble eggs are mostly set but still slightly wet and shiny, 2 to 5 minutes. Remove the eggs to a plate and, if needed, wipe out the pan.

Stir-fry the tomatoes and seasonings:
Add the sesame oil to the pan followed by the tomatoes and stir-fry over medium heat until the tomatoes are softened but not mushy, about 3 minutes. Add the ', 9.45, 'per portion', 41, 'Vegetables', 'South Africa', ARRAY['https://www.themealdb.com/images/media/meals/rwvw8q1765660071.jpg'], '813g', ARRAY[]::TEXT[], '{"calories":383,"protein":25,"carbs":59,"fat":30}'::JSONB, 'This traditional Chinese Tomato Egg Stir Fry has been passed down through generations in South Africa.', TRUE, TRUE, NULL, 4.4, 73, NOW(), NOW()),
    ('5b0b283d-9be4-4f70-bc1c-081fd2a10b93', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Jamaican Steamed Cabbage', 'Add all the ingredients to a large pan over medium heat and cover with a lid.
Cook on medium heat for 10 minutes, stirring occasionally.
After 10 minutes, reduce the heat to low and continue to cook for an additional 5 minutes, until the cabbage is soft and tender. Remove from the heat and remove the stalks of thyme before serving.', 41.46, 'per portion', 64, 'Textiles', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/paejva1765321314.jpg'], '396g', ARRAY['Top Rated'], '{"calories":222,"protein":20,"carbs":22,"fat":9}'::JSONB, 'This traditional Jamaican Steamed Cabbage has been passed down through generations in North Africa.', TRUE, TRUE, 'Best Seller', 4.8, 131, NOW(), NOW()),
    ('3c7e4020-bc15-4a35-90fa-14be9eb3f3b8', '8c593b02-46ae-42ce-ac58-5ef220058850', 'Teriyaki Chicken Casserole', 'Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.
Combine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.
Meanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.
Place the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.
*Meanwhile, steam or cook the vegetables according to package directions.
Add the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserol', 18.55, 'per portion', 92, 'Meats', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg'], '803g', ARRAY['Top Rated'], '{"calories":764,"protein":16,"carbs":80,"fat":13}'::JSONB, 'This traditional Teriyaki Chicken Casserole has been passed down through generations in North Africa.', TRUE, TRUE, 'Limited', 4.2, 81, NOW(), NOW()),
    ('1294c479-35d3-4c04-9552-1ac833a6a9b5', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'Pad Thai', 'step 1
Put the noodles in a large heatproof bowl, pour boiling water over them and leave for 4 minutes, then drain and refresh under cold running water.

step 2
Put the lime juice, cayenne, sugar and fish sauce in a bowl and mix well. Have all the other ingredients ready by the cooker.

step 3
Heat the oil and fry the prawns until warmed through. Add the spring onions and noodles and toss around. Tip in the lime juice mixture, then stir in the beansprouts and half the peanuts and coriander. Cook for 1 minute until everything is heated through.

step 4
Pile into a large dish, scatter with the rest of the peanuts and coriander, and serve with lime wedges and sweet chilli sauce.', 24.49, 'per portion', 53, 'Spices', 'North Africa', ARRAY['https://www.themealdb.com/images/media/meals/rg9ze01763479093.jpg'], '955g', ARRAY['Organic', 'Top Rated'], '{"calories":385,"protein":49,"carbs":40,"fat":24}'::JSONB, 'This traditional Pad Thai has been passed down through generations in North Africa.', TRUE, TRUE, 'Limited', 4.3, 125, NOW(), NOW()),
    ('78ccc62b-c61a-4cf9-84bc-8c95d3d2de35', '27204b60-8d78-4d0a-a5e7-b73716db979b', 'Christmas cake', 'Heat oven to 160C/fan 140C/gas 3. Line the base and sides of a 20 cm round, 7.5 cm deep cake tin. Beat the butter and sugar with an electric hand mixer for 1-2 mins until very creamy and pale in colour, scraping down the sides of the bowl half way through. Stir in a spoonful of the flour, then stir in the beaten egg and the rest of the flour alternately, a quarter at a time, beating well each time with a wooden spoon. Stir in the almonds.

Mix in the sherry (the mix will look curdled), then add the peel, cherries, raisins, cherries, nuts, lemon zest, spice, rosewater and vanilla. Beat together to mix, then stir in the baking powder.

Spoon mixture into the tin and smooth the top, making a slight dip in the centre. Bake for 30 mins, then lower temperature to 150C/fan 130C/gas 2 and bake a further 2-2¼ hrs, until a skewer insterted in the middle comes out clean. Leave to cool in the tin, then take out of the tin and peel off the lining paper. When completely cold, wrap well in cling ', 48.05, 'per portion', 84, 'Meats', 'West Africa', ARRAY['https://www.themealdb.com/images/media/meals/ldnrm91576791881.jpg'], '328g', ARRAY['Eco-Friendly'], '{"calories":251,"protein":27,"carbs":54,"fat":28}'::JSONB, 'This traditional Christmas cake has been passed down through generations in West Africa.', TRUE, FALSE, NULL, 3.9, 119, NOW(), NOW()),
    ('2ff86f9c-d342-4562-ace5-ec8ebf03e426', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'The Origin and Purpose of African Colonization', 'Blyden was President of Liberia College in Monrovia, Liberia. He outlines the reasons for African colonization by American Blacks; founding and purpose of the American Colonization Society; creation of the Colony of Liberia and the current state of the colony--its geographic extent, commerce, and Liberia College. Blyden appeals for more African American colonizers.', 17.62, 'per book', 12, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=B65FiCScw-gC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '710g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4.4, 30, NOW(), NOW()),
    ('e1b02a4d-968e-4070-bd99-e9bc62e01d01', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'African Contribution to Civilization', 'Osei examines the contributions that Africans have made to the arts, sciences, philosophy and religion. In doing so he chronicles and weaves a contextual history. Osei was a diligent self-trained historian, and acutely familiar with all manner books and documents about ancient and modern Africa.', 13.9, 'per book', 38, 'Textiles', 'East Africa', ARRAY['http://books.google.com/books/content?id=NVkfTPz7XhsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '797g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of East Africa.', TRUE, FALSE, NULL, 4.3, 74, NOW(), NOW()),
    ('d70a8370-f19d-4619-8741-5351fb51bd98', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'Transactions - The South African Institute of Electrical Engineers', 'A fascinating book about South Africa', 11.11, 'per book', 22, 'Textiles', 'South Africa', ARRAY['http://books.google.com/books/content?id=47bMmkaSjvQC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '530g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of South Africa.', TRUE, FALSE, NULL, 4.5, 7, NOW(), NOW()),
    ('7011e76f-1580-4f45-95a6-ec517145de7f', '8c593b02-46ae-42ce-ac58-5ef220058850', 'The South African Geographical Journal', 'Vols. for 1932-1940 contain Cape Geographical Society. Report.', 18.65, 'per book', 13, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=lgU_AQAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '608g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4, 85, NOW(), NOW()),
    ('0be3a93d-5159-4bb4-b701-e7107527adf4', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'African administrative studies', 'Issues for 1966- include sections: A. Studies, B. Documents and monographs, C. News of institutes and schools of administration, D. Bibliographical notes.', 27.43, 'per book', 34, 'Textiles', 'West Africa', ARRAY['http://books.google.com/books/content?id=6wkQAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '650g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of West Africa.', TRUE, FALSE, NULL, 4.5, 42, NOW(), NOW()),
    ('6f435a6f-e712-4e4b-b1a2-5a1e0ae7a3b2', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'African studies review', 'A fascinating book about South Africa', 14.92, 'per book', 41, 'Textiles', 'South Africa', ARRAY['http://books.google.com/books/content?id=UH9WAAAAYAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '762g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of South Africa.', TRUE, FALSE, NULL, 4.3, 42, NOW(), NOW()),
    ('7254e511-1b49-414c-a7bf-314649eca04d', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'The North African Church', 'A fascinating book about Central Africa', 12.89, 'per book', 50, 'Textiles', 'Central Africa', ARRAY['http://books.google.com/books/content?id=ZeACAAAAQAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '370g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of Central Africa.', TRUE, FALSE, NULL, 4.1, 72, NOW(), NOW()),
    ('9977da77-16ee-41bb-8e51-fcb8fbd00ab7', '8c593b02-46ae-42ce-ac58-5ef220058850', 'The South African Medical Record', 'A fascinating book about West Africa', 12.05, 'per book', 5, 'Textiles', 'West Africa', ARRAY['http://books.google.com/books/content?id=W9ZXAAAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '675g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of West Africa.', TRUE, TRUE, NULL, 5, 88, NOW(), NOW()),
    ('189cb7c1-42f2-4375-9114-4d8ea2dc3942', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'The African Book of Names', 'From an author who adopted an African name as an adult comes the most inclusive book of African names. Obama, Iman, Kanye, Laila—authentic African names are appearing more often in nurseries, classrooms, and boardrooms. The African Book of Names offers readers more than 5,000 common and uncommon names organized by theme from 37 countries and at least 70 different ethnolinguistic groups. Destined to become a classic keepsake, The African Book of Names shares in-depth insight about the spiritual, ', 15.18, 'per book', 5, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=l92VDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '335g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4.8, 77, NOW(), NOW()),
    ('b86d187e-886c-413b-bac8-7b21c5f2389e', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'Multipartyism and constitutional governance in Africa. How they have failed to address the post-independence governance crisis', 'Seminar paper from the year 2018 in the subject Politics - Region: Africa, grade: 85.0, University of Ghana, Legon, language: English, abstract: This paper presents a brief overview of experiences of multipartyism and constitutional democracy in Africa. It also examines how multipartyism and constitutional rule has failed to address the post-independence governance crisis in Africa. The main position advanced by this paper is that, while constitutional governance and multipartyism have been wide', 16.36, 'per book', 29, 'Textiles', 'West Africa', ARRAY['http://books.google.com/books/content?id=ggYPEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '249g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of West Africa.', TRUE, FALSE, NULL, 4.1, 90, NOW(), NOW()),
    ('4b3e31db-fbe2-4ee9-bfbf-b43f70e8a954', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'African Economic Outlook 2011 Africa and its Emerging Partners', 'This year’s African Economic Outlook reviews recent economic, social and political developments and the short-term likely evolution of Africa. The focus is on Africa''s Emerging Economic Partnerships.', 28.45, 'per book', 31, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=mcBCRPlyYwcC&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '608g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4.4, 77, NOW(), NOW()),
    ('a96c5193-446c-422f-8fed-06846dfb4a27', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'African Notes', 'A fascinating book about South Africa', 13.35, 'per book', 24, 'Textiles', 'South Africa', ARRAY['http://books.google.com/books/content?id=x9hZt5rvq60C&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '248g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of South Africa.', TRUE, FALSE, NULL, 4.1, 10, NOW(), NOW()),
    ('d4202df4-6e4a-47d9-8800-abf9235128f4', '8c593b02-46ae-42ce-ac58-5ef220058850', 'African Statistical Yearbook 1987', 'A fascinating book about Central Africa', 24.46, 'per book', 14, 'Textiles', 'Central Africa', ARRAY['http://books.google.com/books/content?id=0LEUW5d6Ue4C&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '589g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of Central Africa.', TRUE, FALSE, NULL, 4.7, 62, NOW(), NOW()),
    ('89e000c2-b54f-4653-af87-16fd45435539', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'North African historical review', 'Epoque moderne et contemporaine.', 20.97, 'per book', 30, 'Textiles', 'Central Africa', ARRAY['http://books.google.com/books/content?id=sQFxAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '684g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of Central Africa.', TRUE, FALSE, NULL, 4.1, 32, NOW(), NOW()),
    ('380a7328-cbfe-4c1f-bc7c-8ceea6475519', '010d5834-6ba4-4aac-a1fc-c0296c31be86', 'African Grey Parrots', 'Despite its huge size, the handsome and elegant Great Dane is sociable with children, and makes a wonderful pet for owners who have adequate space to give the dog proper exercise. All Complete Pet Owner''s Manuals are heavily illustrated with color photos and line art, and are filled with reliable, easy-to-understand information on pet care. The many titles in this series show and tell pet owners how to care for dogs, cats, birds, fish, reptiles, gerbils, hamsters, and virtually every other anima', 18.43, 'per book', 26, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=1agwCOoKJg8C&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '452g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4, 36, NOW(), NOW()),
    ('5692f42e-e78b-4968-a0ab-03c114243ce0', '8c593b02-46ae-42ce-ac58-5ef220058850', 'The History of the Conquest of Egypt, North Africa and Spain, Known as the Futūḥ Miṣr of Lbn ''Abd Al-Ḥakam', 'A fascinating book about South Africa', 23, 'per book', 43, 'Textiles', 'South Africa', ARRAY['http://books.google.com/books/content?id=s_IlAAAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '797g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of South Africa.', TRUE, FALSE, NULL, 4.1, 64, NOW(), NOW()),
    ('4980829f-1957-4fe0-8434-a4fa23bf7d62', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'South Africa', 'A fascinating book about North Africa', 27.77, 'per book', 13, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=lSwlkLgkZ0IC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '786g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, TRUE, NULL, 4.6, 29, NOW(), NOW()),
    ('2d194c37-5452-4058-9c6c-1338950a665f', 'fad19083-5fa8-4405-941c-3ac0c40aa4c9', 'A History of the African People', 'A fascinating book about West Africa', 13.62, 'per book', 6, 'Textiles', 'West Africa', ARRAY['http://books.google.com/books/content?id=bfUEAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'], '237g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of West Africa.', TRUE, FALSE, NULL, 4.5, 77, NOW(), NOW()),
    ('8b7446ed-fa4f-4a54-9cf0-ba7f29315ae8', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'The Saturday Review of Politics, Literature, Science and Art', 'A fascinating book about Central Africa', 11.64, 'per book', 13, 'Textiles', 'Central Africa', ARRAY['http://books.google.com/books/content?id=otgtlLByKZUC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '569g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of Central Africa.', TRUE, FALSE, NULL, 4.3, 36, NOW(), NOW()),
    ('154dfa16-30e3-48a9-94ca-0e918907d352', '286d503b-560f-46a3-b877-b6b5edae2038', 'The Contemporary Review', 'A fascinating book about North Africa', 17.66, 'per book', 34, 'Textiles', 'North Africa', ARRAY['http://books.google.com/books/content?id=HJDQAAAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'], '768g', ARRAY[]::TEXT[], NULL::JSONB, 'This book explores the rich culture and heritage of North Africa.', TRUE, FALSE, NULL, 4, 82, NOW(), NOW()),
    ('7d25ed09-778f-4827-a426-9a8e73365a4d', 'c3cb8d2a-4fed-4c01-9a9b-4873aacdd17f', 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 109.95, 'per item', 151, 'Textiles', 'South Africa', ARRAY['https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png'], '1173g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from South Africa.', TRUE, FALSE, NULL, 3.9, 120, NOW(), NOW()),
    ('86aa25f6-b134-4ce4-91cc-314aa4771f19', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'Mens Casual Premium Slim Fit T-Shirts ', 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 22.3, 'per item', 142, 'Textiles', 'Central Africa', ARRAY['https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png'], '1392g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from Central Africa.', TRUE, FALSE, NULL, 4.1, 259, NOW(), NOW()),
    ('8956d630-a78d-4d45-97d5-33c9bc315e7b', '8c593b02-46ae-42ce-ac58-5ef220058850', 'Mens Cotton Jacket', 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 55.99, 'per item', 128, 'Textiles', 'West Africa', ARRAY['https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png'], '1750g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from West Africa.', TRUE, TRUE, 'Best Seller', 4.7, 500, NOW(), NOW()),
    ('f23946a3-ef3c-4645-a344-cca71743f443', '8c593b02-46ae-42ce-ac58-5ef220058850', 'Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', 15.99, 'per item', 183, 'Textiles', 'North Africa', ARRAY['https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png'], '465g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from North Africa.', TRUE, FALSE, NULL, 2.1, 430, NOW(), NOW()),
    ('4aff91fc-411d-41b0-84f0-df139ad226ff', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', 695, 'per item', 27, 'Textiles', 'East Africa', ARRAY['https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png'], '1987g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from East Africa.', TRUE, TRUE, NULL, 4.6, 400, NOW(), NOW()),
    ('7c096299-a34f-4357-b9dc-056c162a323b', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Solid Gold Petite Micropave ', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 168, 'per item', 29, 'Textiles', 'East Africa', ARRAY['https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png'], '873g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from East Africa.', TRUE, FALSE, NULL, 3.9, 70, NOW(), NOW()),
    ('d829f922-a7be-427a-a524-6001efb25123', '8c593b02-46ae-42ce-ac58-5ef220058850', 'White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...', 9.99, 'per item', 98, 'Textiles', 'Central Africa', ARRAY['https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png'], '1725g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from Central Africa.', TRUE, FALSE, NULL, 3, 400, NOW(), NOW()),
    ('91c9ab6a-0866-48cc-9dc3-d38be0553d7d', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 10.99, 'per item', 116, 'Textiles', 'South Africa', ARRAY['https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png'], '988g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from South Africa.', TRUE, FALSE, NULL, 1.9, 100, NOW(), NOW()),
    ('9a11d188-c29e-4544-b0f6-0fa8b9a9941d', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'WD 2TB Elements Portable External Hard Drive - USB 3.0 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 64, 'per item', 192, 'Beverages', 'East Africa', ARRAY['https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png'], '899g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from East Africa.', TRUE, FALSE, NULL, 3.3, 203, NOW(), NOW()),
    ('682494c2-7119-4498-a8ea-57f6b970374a', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 109, 'per item', 80, 'Beverages', 'North Africa', ARRAY['https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png'], '520g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from North Africa.', TRUE, TRUE, NULL, 2.9, 470, NOW(), NOW()),
    ('76390456-5309-44d9-a4ed-46afca39c548', '2b0ad20a-ff81-471e-b1ba-e491c5e7ab09', 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.', 109, 'per item', 157, 'Beverages', 'West Africa', ARRAY['https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png'], '1726g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from West Africa.', TRUE, FALSE, NULL, 4.8, 319, NOW(), NOW()),
    ('298ecafd-8866-4a9e-b357-99b91eac26ba', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty', 114, 'per item', 157, 'Beverages', 'West Africa', ARRAY['https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png'], '1146g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from West Africa.', TRUE, FALSE, NULL, 4.8, 400, NOW(), NOW()),
    ('87a1bafc-9d8e-46ce-941f-45fabee4e2e0', '0e130aae-0e69-401c-a49b-eb79fcf1c1ea', 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz', 599, 'per item', 141, 'Beverages', 'West Africa', ARRAY['https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png'], '1997g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from West Africa.', TRUE, FALSE, NULL, 2.9, 250, NOW(), NOW()),
    ('940ce031-936d-4fb9-92c0-2cb71591f80d', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ', '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag', 999.99, 'per item', 15, 'Beverages', 'Central Africa', ARRAY['https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png'], '1632g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from Central Africa.', TRUE, TRUE, NULL, 2.2, 140, NOW(), NOW()),
    ('a9ed8a2e-9aa3-4e01-b34a-3b28372fb5ff', '27204b60-8d78-4d0a-a5e7-b73716db979b', 'BIYLACLESEN Women''s 3-in-1 Snowboard Jacket Winter Coats', 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates', 56.99, 'per item', 169, 'Textiles', 'West Africa', ARRAY['https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png'], '1166g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from West Africa.', TRUE, FALSE, NULL, 2.6, 235, NOW(), NOW()),
    ('d6f75b02-5a0e-42e7-8739-3925438ef04b', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'Lock and Love Women''s Removable Hooded Faux Leather Moto Biker Jacket', '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON', 29.95, 'per item', 143, 'Textiles', 'East Africa', ARRAY['https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png'], '1305g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from East Africa.', TRUE, FALSE, 'Best Seller', 2.9, 340, NOW(), NOW()),
    ('c6b0ebed-830b-4fdb-816d-169bc1c72a41', '8c593b02-46ae-42ce-ac58-5ef220058850', 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn''t overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', 39.99, 'per item', 62, 'Textiles', 'South Africa', ARRAY['https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png'], '1614g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from South Africa.', TRUE, FALSE, 'Best Seller', 3.8, 679, NOW(), NOW()),
    ('26cfbb6c-ee19-413b-850e-9b203145f1d0', 'f7b0c3c3-3a58-48c5-bfbd-6ba217702223', 'MBJ Women''s Solid Short Sleeve Boat Neck V ', '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem', 9.85, 'per item', 76, 'Textiles', 'East Africa', ARRAY['https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png'], '1692g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from East Africa.', TRUE, FALSE, NULL, 4.7, 130, NOW(), NOW()),
    ('dfefd298-5274-448b-9152-e20bba0267cc', '286d503b-560f-46a3-b877-b6b5edae2038', 'Opna Women''s Short Sleeve Moisture', '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort', 7.95, 'per item', 47, 'Textiles', 'North Africa', ARRAY['https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png'], '110g', ARRAY['Top Rated'], NULL::JSONB, 'Authentic product sourced from North Africa.', TRUE, FALSE, NULL, 4.5, 146, NOW(), NOW()),
    ('c7a0ef68-7766-40dd-b64b-1e8f29f0ec75', 'f1f9973c-10a7-4186-b9a1-08d42fc38ea2', 'DANVOUY Womens T Shirt Casual Cotton Short', '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.', 12.99, 'per item', 28, 'Textiles', 'Central Africa', ARRAY['https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png'], '1892g', ARRAY[]::TEXT[], NULL::JSONB, 'Authentic product sourced from Central Africa.', TRUE, FALSE, NULL, 3.6, 145, NOW(), NOW())
ON CONFLICT DO NOTHING;


COMMIT;

-- Summary:
-- Vendors: 20
-- Products: 70
